theme: jekyll-theme-cayman
markdown: kramdown
destination: ../docs
github:
    repository_url: https://github.com/telereso/telereso.git

build_revision: ${version}
google_analytics: G-V8S2X6JQZM
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
