targets:
    $default:
        builders:
            telereso_generator|telereso:
                enabled: true

builders:
  telereso:
      target: ":telereso_generator"
      import: "package:telereso_generator/telereso_generator.dart"
      builder_factories: ["remoteLocalizationBuilder"]
      build_extensions: {".arb":["remote_localization.telereso.dart"]}
      auto_apply: dependents
      build_to: source
      applies_builders: ["source_gen|combining_builder"]
      defaults:
          options:
              template-arb-file: intl_en.arb
              output-class-remote: RemoteLocalizationsDefault


#  telereso:
#      target: ":telereso_generator"
#      import: "package:telereso_generator/builder.dart"
#      builder_factories: ["remoteLocalization"]
#      build_extensions: {".dart":[".remote_localization.g.part"]}
#      auto_apply: dependents
#      build_to: cache
#      applies_builders: ["source_gen|combining_builder"]