name: telereso_generator
version: 0.0.1
author: Swav Kulinski<swav.kulinski@gmail.com>
repository: 
environment: 
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  build: ^1.6.1
  source_gen: ^0.9.10+1
  telereso:
    path: ../flutter_telereso/

dev_dependencies:
  test: ^1.15.7

  
