# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Lists' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lists
  pod 'Telereso', :path => '../../ios'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'

  target 'ListsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ListsUITests' do
    # Pods for testing
  end

end
