targets:
  $default:
    builders:
      telereso_generator|telereso:
        enabled: true
        options:
          template-arb-file: intl_en.arb
          output-localization-file: gallery_localizations.dart
          output-class: GalleryLocalizations
          output-class-remote: RemoteLocalizationsDefault
