name: Web pull requests

# Controls when the workflow will run
on: 
  workflow_dispatch:
  pull_request:
   paths:
     - 'web/**'
     - 'Samples/web/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-react
        with:
          path: |
           web/node_modules
           Samples/web/node_modules
          key: ${{ runner.OS }}-react-install-cache   
      
      - name: Install node modules
        run: cd Samples/web && yarn install --frozen-lockfile  
      
      - name: Prepare Secrets
        env:
         WEB_ENV: ${{ secrets.SAMPLES_WEB_ENV }}
        run: echo "$WEB_ENV" > Samples/web/.env
      
      - name: Build with Gradle
        run: cd Samples/web/ && yarn build
      
      - name: Archive webstie
        uses: actions/upload-artifact@v2 
        with:
          name: test-apk
          path: Samples/web/build/
          retention-days: 2
